spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC
    username: root
    password: root
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  type-aliases-package: com.com.fu.entity #entity别名类
  mapper-locations:
    classpath:mapper/**/*.xml #mapper映射文件